<<<<<<< HEAD
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main sidebar with Module 1 and tutorial content
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2/chapter-1-intro-physical-ai',
        'module-1-ros2/chapter-2-ros2-architecture',
        'module-1-ros2/chapter-3-python-nodes',
        'module-1-ros2/chapter-4-packages-launch',
        'module-1-ros2/chapter-5-urdf',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2-digital-twin/chapter-1-foundations',
        'module-2-digital-twin/chapter-2-gazebo-physics',
        'module-2-digital-twin/chapter-3-robot-models',
        'module-2-digital-twin/chapter-4-sensor-simulation',
        'module-2-digital-twin/chapter-5-unity-hri',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-3-isaac-ai/chapter-1-isaac-overview',
        'module-3-isaac-ai/chapter-2-synthetic-data',
        'module-3-isaac-ai/chapter-3-accelerated-perception',
        'module-3-isaac-ai/chapter-4-navigation-nav2',
        'module-3-isaac-ai/chapter-5-sim-to-real',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4-vla/chapter-1-vla-foundations',
        'module-4-vla/chapter-2-voice-to-action',
        'module-4-vla/chapter-3-llm-planning',
        'module-4-vla/chapter-4-multimodal-fusion',
        'module-4-vla/chapter-5-capstone',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Tutorial',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
  ],
};

export default sidebars;
=======
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main sidebar with Module 1 and tutorial content
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2/chapter-1-intro-physical-ai',
        'module-1-ros2/chapter-2-ros2-architecture',
        'module-1-ros2/chapter-3-python-nodes',
        'module-1-ros2/chapter-4-packages-launch',
        'module-1-ros2/chapter-5-urdf',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2-digital-twin/chapter-1-foundations',
        'module-2-digital-twin/chapter-2-gazebo-physics',
        'module-2-digital-twin/chapter-3-robot-models',
        'module-2-digital-twin/chapter-4-sensor-simulation',
        'module-2-digital-twin/chapter-5-unity-hri',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-3-isaac-ai/chapter-1-isaac-overview',
        'module-3-isaac-ai/chapter-2-synthetic-data',
        'module-3-isaac-ai/chapter-3-accelerated-perception',
        'module-3-isaac-ai/chapter-4-navigation-nav2',
        'module-3-isaac-ai/chapter-5-sim-to-real',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4-vla/chapter-1-vla-foundations',
        'module-4-vla/chapter-2-voice-to-action',
        'module-4-vla/chapter-3-llm-planning',
        'module-4-vla/chapter-4-multimodal-fusion',
        'module-4-vla/chapter-5-capstone',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Tutorial',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
  ],
};

export default sidebars;
>>>>>>> 5cf5f6818272e652910633754d301908ff0bb236
